---
- name: configuration check
  block:
    - name: check nginx configuration
      command: nginx -t
      ignore_errors: true
      register: nginx_syntax_check
      changed_when: false

    - name: show errors
      debug:
        msg: "{{ nginx_syntax_check.stderr }}"
      when: nginx_syntax_check.rc != 0

    - name: Notify if bad syntax
      assert:
        that:
          - nginx_syntax_check.rc == 0
        fail_msg: "Nginx configuration check failed. You should check debug information above and fix the problem(s)."

    - name: reload nginx
      command: nginx -s reload
      when: nginx_syntax_check.rc == 0
  when: not ansible_check_mode
